Parameters:
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String
  LayerS3Bucket:
    Type: String
  LayerS3Key:
    Type: String
  
Resources:
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: !Ref LayerS3Bucket
        S3Key: !Ref LayerS3Key
        S3ObjectVersion: !Ref LayerS3ObjectVersion
      CompatibleRuntimes:
        - python3.12
      Description: Dependencies from requires.txt
      LicenseInfo: MIT


  HelloWorldLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hello-world-lambda-pipeline
      Handler: index.handler
      Role: arn:aws:iam::132502993358:role/lambda-full-access
      Runtime: python3.12
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Timeout: 10
      MemorySize: 128
      Description: "Lambda using a layer built from requires.txt"
      Layers:
        - !Ref LambdaLayer

  HelloWorldLambda2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hello-world-lambda2-pipeline
      Handler: lambda_function.handler2
      Role: arn:aws:iam::132502993358:role/lambda-full-access
      Runtime: python3.12
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Timeout: 10
      MemorySize: 128
      Description: "Lambda using a layer built from requires.txt"
      Layers:
        - !Ref LambdaLayer
Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref HelloWorldLambda
  LambdaLayerArn:
    Description: Latest published Lambda Layer version ARN
    Value: !Ref LambdaLayer
