AWSTemplateFormatVersion: '2010-09-09'
Description: Publishes a Lambda Layer from an S3 object and exports the latest LayerVersion ARN

Parameters:
  LayerName:
    Type: String
    Default: lambda-layer
    Description: Logical name for the Lambda Layer
  CompatibleRuntimes:
    Type: CommaDelimitedList
    Default: python3.12
    Description: Comma-separated runtimes (e.g., python3.12,python3.11)
  LayerS3Bucket:
    Type: String
    Description: S3 bucket that holds the layer zip (must be versioned)
  LayerS3Key:
    Type: String
    Description: S3 key for the layer zip (e.g., layers/<hash>.zip)
  LayerS3ObjectVersion:
    Type: String
    Description: Specific S3 object VersionId for the layer zip
  ExportNameSuffix:
    Type: String
    Default: LatestLayerVersionArn
    Description: Suffix for the exported value name; full name becomes <stack-name>-<suffix>

Resources:
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: Lambda Layer built from requirements.txt
      CompatibleRuntimes: !Ref CompatibleRuntimes
      Content:
        S3Bucket: !Ref LayerS3Bucket
        S3Key: !Ref LayerS3Key
        S3ObjectVersion: !Ref LayerS3ObjectVersion
      CompatibleArchitectures:
        - x86_64


Outputs:
  LatestLayerVersionArn:
    Description: ARN of the latest published LayerVersion
    Value: !Ref LambdaLayer           # Ref on LayerVersion returns the version ARN
    Export:
      Name: !Sub '${AWS::StackName}-${ExportNameSuffix}'
