Parameters:
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String

Resources:
  HelloWorldLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hello-world-lambda
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-execution-role
      Runtime: python3.12
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Timeout: 10
      MemorySize: 128
